import { jsPDF } from "jspdf";

// Server-side port of creator.js/brand.js's downloadAgreementPDF() (which
// ran client-side via a CDN-loaded jsPDF). Moved server-side per plan
// deviation #4 so the Shield-only-download gate is enforced by the server
// re-checking shield_active before generating bytes, not just by hiding a
// button — see app/api/agreements/[agreementId]/pdf/route.ts.
export function buildAgreementPdf(input: {
  brandName: string;
  creatorName: string;
  title: string | null;
  platform: string | null;
  amount: number | null;
  deliverables: string | null;
  usageRights: string | null;
  paymentTerms: string | null;
  deadline: string | null;
  generatedAt: string | null;
}): Buffer {
  const doc = new jsPDF();
  let y = 20;

  doc.setFont("helvetica", "bold").setFontSize(20).text("ZEKE", 20, y);
  y += 8;
  doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(120).text("Legally Protected Influencer Marketplace", 20, y);
  y += 14;
  doc.setTextColor(0).setFontSize(14).setFont("helvetica", "bold").text("Deal Agreement", 20, y);
  y += 10;
  doc.setFontSize(10).setFont("helvetica", "normal");

  const lines: [string, string][] = [
    ["Brand", input.brandName],
    ["Creator", input.creatorName],
    ["Title", input.title || "—"],
    ["Platform", input.platform || "—"],
    ["Value", `₹${input.amount || 0}`],
    ["Deliverables", input.deliverables || "—"],
    ["Usage rights", input.usageRights || "As agreed"],
    ["Payment terms", input.paymentTerms || "On completion"],
    ["Deadline", input.deadline || "As agreed"],
    ["Generated", input.generatedAt ? new Date(input.generatedAt).toLocaleString() : "—"],
  ];

  for (const [label, value] of lines) {
    doc.setFont("helvetica", "bold").text(`${label}:`, 20, y);
    const wrapped = doc.splitTextToSize(String(value), 140);
    doc.setFont("helvetica", "normal").text(wrapped, 60, y);
    y += Math.max(8, wrapped.length * 6);
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
  }

  y += 6;
  doc.setFontSize(9).setTextColor(120);
  const disclaimer = doc.splitTextToSize(
    "This agreement is generated by Zeke based on the deal terms accepted by both parties. Both parties confirmed acceptance digitally on the platform. Any dispute will be reviewed by the Zeke team for Shield members.",
    170
  );
  doc.text(disclaimer, 20, y);

  return Buffer.from(doc.output("arraybuffer"));
}
